In [5]:
# Get the hisotrical weanther data for games played
import pandas as pd
import requests
import time
from pprint import pprint
from mike_api import api_key
# create code to test the WorldWeatherOnline API


# url = HTTPS: https://api.worldweatheronline.com/premium/v1/past-weather.ashx
# example request url . 
#URL http://api.worldweatheronline.com/premium/v1/past_weather.ashx?q=London&amp;format=xml&amp;key=xxxxxxxxxxxxxxxxx
game_data_toload = "stadiums_merge_type.csv"
game_data = pd.read_csv(game_data_toload)
game_data.head()


cityid = game_data['CITY']
game_date = game_data['SCHEDULE DATE']
#game_date = ['2014-09-07', '2014-09-14', '2014-09-21', '2014-09-28']
temp = []
description = []
weather_code = []
location = []
date = []
game_date
#start = time.mktime(datetime.datetime.strptime(game_date, "%d/%m/%Y").timetuple())

# format_url = f"{url}{cityid}&date={game_date}&format=json&key={api_key}"
#print(format_url)

0      09/13/2015
1      09/27/2015
2      10/04/2015
3      10/26/2015
4      11/22/2015
5      12/10/2015
6      12/27/2015
7      01/03/2016
8             NaN
9             NaN
10            NaN
11     09/13/2015
12     10/04/2015
13     11/01/2015
14     11/15/2015
15     11/29/2015
16     12/13/2015
17     12/28/2015
18     01/03/2016
19     09/13/2015
20     09/20/2015
21     10/18/2015
22     10/25/2015
23     11/19/2015
24     11/29/2015
25     12/13/2015
26     12/20/2015
27            NaN
28     09/13/2015
29     10/04/2015
          ...
134    10/25/2015
135    11/15/2015
136    11/29/2015
137    12/06/2015
138    12/27/2015
139    09/13/2015
140    09/27/2015
141    10/11/2015
142    11/01/2015
143    11/08/2015
144    11/26/2015
145    12/19/2015
146    01/03/2016
147    09/13/2015
148    09/27/2015
149    10/08/2015
150    11/01/2015
151    11/22/2015
152    11/29/2015
153    12/13/2015
154    01/03/2016
155           NaN
156    09/20/2015
157    09/28/2015
158    10/11/2015
159    10/18/2015
160    11/15/2015
161    11/26/2015
162    12/13/2015
163    01/03/2016
Name: SCHEDULE DATE, Length: 164, dtype: object

In [ ]:
url = 'https://api.worldweatheronline.com/premium/v1/past-weather.ashx?q='

count = 0
#request_url = f"{url}{cityid}&date={game_date}&format=json&key={api_key}"
#weather = requests.get(request_url).json()

# loop in loop to request weather data for each NFL city on each game day.

for day in game_date:
    try:
        for city in cityid:
            try:
                count += 1
                request_url = f"{url}{city},US&date={day}&format=json&key={api_key}"
                weather = requests.get(request_url).json()
                location.append(city)
                date.append(day)
                temp.append(weather['data']['weather'][0]['hourly'][6]['FeelsLikeF'])
                description.append(weather['data']['weather'][0]['hourly'][6]['weatherDesc'][0]['value'])
                weather_code.append(weather['data']['weather'][0]['hourly'][6]['weatherCode'])
                #pprint(weather)
            except:
                print("No game in City this week")
    except:
        print("No date found")
print(temp)
print(description)
print(weather_code)

In [3]:
# Create a dictionary from the weather data lists. Used to create dataframe


weather_dict = {
    'Game Date': date,
    'City': location,
    'Temperature': temp,
    'Weather': description, 
    'Code': weather_code
}
#weather_dict

# create a data frame from arrays filled by responses
weather_df = pd.DataFrame(weather_dict)
weather_df.to_csv('weather_data.csv')
weather_df

    Game Date           City Temperature               Weather Code
0  2014-09-07  charlotte, NC          87  Patchy rain possible  176
1  2014-09-07      green bay          69                 Clear  113
2  2014-09-14  charlotte, NC          76                Cloudy  119
3  2014-09-14      green bay          59         Partly cloudy  116
4  2014-09-21  charlotte, NC          87                 Clear  113
5  2014-09-21      green bay          53                 Clear  113
6  2014-09-28  charlotte, NC          84                 Clear  113
7  2014-09-28      green bay          74                 Clear  113